-- MySQL Script generated by MySQL Workbench
-- 09/13/15 02:14:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema renap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema renap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `renap` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `renap` ;

-- -----------------------------------------------------
-- Table `renap`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`pais` ;

CREATE TABLE IF NOT EXISTS `renap`.`pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `code` VARCHAR(6) NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`departamento` ;

CREATE TABLE IF NOT EXISTS `renap`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`municipio` ;

CREATE TABLE IF NOT EXISTS `renap`.`municipio` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `id_departamento` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_municipio_departamento_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_municipio_departamento`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `renap`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`persona` ;

CREATE TABLE IF NOT EXISTS `renap`.`persona` (
  `dpi` CHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `segundo_nombre` VARCHAR(50) NULL,
  `tercer_nombre` VARCHAR(50) NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `genero` ENUM('f', 'm') NOT NULL,
  `nacimiento` DATE NOT NULL,
  `id_municipio` INT NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `id_pais` INT NULL,
  `fecha_creacion` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `creacion` INT NOT NULL,
  `fecha_modificacion` DATETIME ON UPDATE CURRENT_TIMESTAMP,
  `muerto` TINYINT(1) NULL DEFAULT 0,
  `eliminado` TINYINT(1) NOT NULL,
  `registrado_por` CHAR(10) NULL,
  PRIMARY KEY (`dpi`),
  INDEX `fk_persona_pais1_idx` (`id_pais` ASC),
  INDEX `fk_persona_municipio1_idx` (`id_municipio` ASC),
  CONSTRAINT `fk_persona_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `renap`.`pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `renap`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`tipo_parentesco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`tipo_parentesco` ;

CREATE TABLE IF NOT EXISTS `renap`.`tipo_parentesco` (
  `tipo_parentesco` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`tipo_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`parentesco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`parentesco` ;

CREATE TABLE IF NOT EXISTS `renap`.`parentesco` (
  `dpi` CHAR(10) NOT NULL,
  `dpi_relacion` CHAR(10) NOT NULL,
  `tipo_parentesco` INT NOT NULL,
  PRIMARY KEY (`dpi`, `dpi_relacion`, `tipo_parentesco`),
  INDEX `fk_parentesco_tipo_parentesco1_idx` (`tipo_parentesco` ASC),
  INDEX `fk_parentesco_persona2_idx` (`dpi_relacion` ASC),
  CONSTRAINT `fk_parentesco_tipo_parentesco1`
    FOREIGN KEY (`tipo_parentesco`)
    REFERENCES `renap`.`tipo_parentesco` (`tipo_parentesco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parentesco_persona1`
    FOREIGN KEY (`dpi`)
    REFERENCES `renap`.`persona` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parentesco_persona2`
    FOREIGN KEY (`dpi_relacion`)
    REFERENCES `renap`.`persona` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`estado_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`estado_documento` ;

CREATE TABLE IF NOT EXISTS `renap`.`estado_documento` (
  `idestado_documento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idestado_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`dpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`dpi` ;

CREATE TABLE IF NOT EXISTS `renap`.`dpi` (
  `id_dpi` INT NOT NULL AUTO_INCREMENT,
  `dpi` CHAR(10) NOT NULL,
  `fecha_emision` DATETIME NOT NULL DEFAULT NOW(),
  `fecha_vencimiento` DATE NOT NULL,
  `estado_documento` INT NOT NULL,
  PRIMARY KEY (`id_dpi`),
  INDEX `fk_dpi_estado_documento1_idx` (`estado_documento` ASC),
  INDEX `fk_dpi_persona1_idx` (`dpi` ASC),
  CONSTRAINT `fk_dpi_estado_documento1`
    FOREIGN KEY (`estado_documento`)
    REFERENCES `renap`.`estado_documento` (`idestado_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dpi_persona1`
    FOREIGN KEY (`dpi`)
    REFERENCES `renap`.`persona` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`usuario` ;

CREATE TABLE IF NOT EXISTS `renap`.`usuario` (
  `usuario` VARCHAR(40) NOT NULL,
  `passwd` VARCHAR(200) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT now(),
  `bloqueado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`reporte_denuncia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`reporte_denuncia` ;

CREATE TABLE IF NOT EXISTS `renap`.`reporte_denuncia` (
  `idreporte_denuncia` INT NOT NULL,
  PRIMARY KEY (`idreporte_denuncia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`cliente_api`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`cliente_api` ;

CREATE TABLE IF NOT EXISTS `renap`.`cliente_api` (
  `clave_secreta` INT NOT NULL,
  `nombre_entidad` VARCHAR(150) NOT NULL,
  `bloqueada` TINYINT(1) NOT NULL DEFAULT 1,
  `contacto` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`clave_secreta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `renap`.`historial_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `renap`.`historial_persona` ;

CREATE TABLE IF NOT EXISTS `renap`.`historial_persona` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `dpi` CHAR(10) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `segundo_nombre` VARCHAR(50) NULL,
  `tercer_nombre` VARCHAR(50) NULL,
  `primer_apellido` VARCHAR(50) NULL,
  `segundo_apellido` VARCHAR(50) NULL,
  `direccion` VARCHAR(45) NULL,
  `genero` ENUM('f', 'm') NULL,
  `municipio` INT NULL,
  `muerto` TINYINT(1) NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `fk_historial_persona_persona1_idx` (`dpi` ASC),
  CONSTRAINT `fk_historial_persona_persona1`
    FOREIGN KEY (`dpi`)
    REFERENCES `renap`.`persona` (`dpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
